# Generated by Django 5.2.4 on 2025-08-02 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateField(blank=True, default=None, null=True)),
                ('csrf_token', models.TextField(blank=True, default=None, null=True)),
                ('en_attente_confirmation', models.BooleanField(blank=True, default=True)),
                ('reinitialisation_password', models.BooleanField(blank=True, default=False)),
                ('autorise_modif', models.BooleanField(blank=True, default=True)),
                ('doit_changer_mdp', models.BooleanField(blank=True, default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
